# SSlogs AI模型配置文件
# 支持LM Studio本地大语言模型配置

# LM Studio 连接配置
lm_studio:
  # 基本连接设置
  host: "127.0.0.1"
  port: 1234
  timeout: 30
  retry_attempts: 3
  retry_delay: 1.0

  # API配置（支持OpenAI兼容格式）
  api:
    # API基础路径
    base_url: "http://127.0.0.1:1234/v1"

    # 自定义API端点（留空使用默认）
    chat_endpoint: "/chat/completions"
    models_endpoint: "/models"

    # API认证（如果需要）
    api_key: ""  # 通常LM Studio不需要

    # 请求头配置
    headers:
      Content-Type: "application/json"
      # User-Agent: "SSlogs-AI/1.0"

  # 模型配置
  model:
    # 首选模型（支持自定义模型名称）
    preferred_model: ""

    # 自定义模型名称映射（实际模型ID -> 显示名称）
    model_mapping:
      # 示例：将LM Studio中的模型ID映射为自定义名称
      # "llama-3-8b-instruct": "openai/gpt-oss-20b"
      # "qwen-7b-chat": "custom/security-analyzer-v1"
      # 确保openai/gpt-oss-20b模型名称可以直接使用（无需映射）

    # 模型参数
    max_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    frequency_penalty: 0.0
    presence_penalty: 0.0

    # 流式输出配置
    stream: false

    # 响应格式
    response_format:
      type: "text"  # text, json_object

  # 缓存配置
  cache:
    enabled: true
    ttl: 3600  # 缓存时间（秒）
    max_size: 1000  # 最大缓存条目数

# AI分析功能开关
ai_features:
  # 启用AI增强威胁分析
  threat_analysis: true

  # 启用自然语言查询
  natural_language_query: true

  # 启用规则解释
  rule_explanation: true

  # 启用安全建议生成
  security_recommendations: true

  # 启用批量分析
  batch_analysis: true

# 分析配置
analysis:
  # 威胁评分权重配置
  scoring_weights:
    # AI分析与规则匹配的权重
    ai_weight: 0.4
    rule_weight: 0.6

    # 威胁等级映射
    threat_levels:
      critical: 9.5
      high: 7.5
      medium: 5.5
      low: 3.5

  # 分析阈值
  thresholds:
    # AI置信度阈值（低于此值的结果将被忽略）
    confidence_threshold: 0.3

    # 威胁评分阈值（低于此值不认为是恶意）
    threat_score_threshold: 5.0

    # 处理时间阈值（秒）
    processing_time_threshold: 10.0

# 性能配置
performance:
  # 并发配置
  max_concurrent_requests: 5
  batch_size: 10

  # 超时配置
  request_timeout: 30
  batch_timeout: 60

  # 资源限制
  max_memory_usage: "1GB"
  max_cpu_usage: 50

# 日志配置
logging:
  # AI分析日志级别
  level: "INFO"

  # 详细日志记录
  detailed_logging: false

  # 记录AI请求和响应
  log_requests: false
  log_responses: false

# 安全配置
security:
  # 敏感信息过滤
  filter_sensitive_data: true

  # 敏感字段列表
  sensitive_fields:
    - "password"
    - "token"
    - "api_key"
    - "secret"
    - "credential"
    - "session"
    - "cookie"
    - "authorization"
    - "auth"

# 预设配置模板
presets:
  # 高精度分析（低温度，高准确性）
  high_precision:
    temperature: 0.2
    max_tokens: 1024
    top_p: 0.8
    confidence_threshold: 0.7

  # 快速分析（高温度，快速响应）
  fast_analysis:
    temperature: 0.8
    max_tokens: 512
    top_p: 0.95
    confidence_threshold: 0.3

  # 平衡模式（默认配置）
  balanced:
    temperature: 0.5
    max_tokens: 1024
    top_p: 0.9
    confidence_threshold: 0.5

# 自定义提示词模板
prompts:
  # 威胁分析系统提示词
  threat_analysis_system: |
    你是一个专业的网络安全分析师，具有多年的实战经验。
    请分析以下日志条目，识别潜在的安全威胁、攻击模式或异常行为。

    分析要求：
    1. 威胁等级评估（低/中/高/严重）
    2. 攻击类型识别
    3. 风险因素分析
    4. 建议的响应措施

    请用中文回答，保持专业和准确。优先考虑实际的威胁而非理论可能性。

  # 自然语言查询系统提示词
  nlp_system: |
    你是一个安全数据分析助手，专门帮助用户理解和分析安全日志。
    请用专业但易懂的语言回答用户问题，提供有价值的分析结果。

    回答要求：
    1. 直接回答用户问题
    2. 提供相关的安全分析
    3. 发现的威胁模式
    4. 建议的进一步分析方向

    请用中文回答，保持专业和有帮助。

  # 规则解释系统提示词
  rule_explanation_system: |
    你是一个安全规则专家，擅长解释各种安全检测规则的工作原理。
    请详细解释为什么特定规则会匹配到某个日志条目，以及这个匹配的安全意义。

    解释要求：
    1. 规则匹配的具体原因
    2. 检测到的攻击模式
    3. 威胁评估
    4. 业务影响分析

    请用中文回答，保持专业且易懂。

# 模型兼容性配置
model_compatibility:
  # 支持的模型系列
  supported_series:
    - "llama"
    - "qwen"
    - "chatglm"
    - "mistral"
    - "mixtral"
    - "yi"
    - "deepseek"
    - "baichuan"

  # 模型大小偏好（GB）
  preferred_sizes:
    - 7
    - 13
    - 34
    - 70

  # 避免的模型特征
  avoid_features:
    - "base"  # 基础模型，指令调优模型更好
    - "raw"   # 原始模型

# 集成配置
integrations:
  # 与其他系统的集成
  external_systems:
    siem:
      enabled: false
      endpoint: ""
      api_key: ""

    ticketing:
      enabled: false
      endpoint: ""
      api_key: ""

  # Webhook配置
  webhooks:
    threat_detected:
      enabled: false
      url: ""
      headers: {}

    analysis_completed:
      enabled: false
      url: ""
      headers: {}